package pojos;
// Generated Feb 2, 2019 9:01:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Automobile generated by hbm2java
 */
public class Automobile  implements java.io.Serializable {


     private String vin;
     private int year;
     private String make;
     private String model;
     private String body;
     private String color;
     private Set purchases = new HashSet(0);

    public Automobile() {
    }

	
    public Automobile(String vin, int year, String make, String model, String body, String color) {
        this.vin = vin;
        this.year = year;
        this.make = make;
        this.model = model;
        this.body = body;
        this.color = color;
    }
    public Automobile(String vin, int year, String make, String model, String body, String color, Set purchases) {
       this.vin = vin;
       this.year = year;
       this.make = make;
       this.model = model;
       this.body = body;
       this.color = color;
       this.purchases = purchases;
    }
   
    public String getVin() {
        return this.vin;
    }
    
    public void setVin(String vin) {
        this.vin = vin;
    }
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }
    public String getMake() {
        return this.make;
    }
    
    public void setMake(String make) {
        this.make = make;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Set getPurchases() {
        return this.purchases;
    }
    
    public void setPurchases(Set purchases) {
        this.purchases = purchases;
    }

    @Override
    public String toString() {
        return "Automobile{" + "vin=" + vin + ", year=" + year + ", make=" + make + ", model=" + model + ", body=" + body + ", color=" + color + ", purchases=" + purchases + '}';
    }

}


