package pojos;
// Generated Feb 2, 2019 9:01:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private String customerKey;
     private String lastName;
     private String firstName;
     private String phone;
     private String street1;
     private String street2;
     private String city;
     private String state;
     private String zipcode;
     private Set purchases = new HashSet(0);

    public Customer() {
    }

	
    public Customer(String customerKey, String lastName, String firstName, String phone) {
        this.customerKey = customerKey;
        this.lastName = lastName;
        this.firstName = firstName;
        this.phone = phone;
    }
    public Customer(String customerKey, String lastName, String firstName, String phone, String street1, String street2, String city, String state, String zipcode, Set purchases) {
       this.customerKey = customerKey;
       this.lastName = lastName;
       this.firstName = firstName;
       this.phone = phone;
       this.street1 = street1;
       this.street2 = street2;
       this.city = city;
       this.state = state;
       this.zipcode = zipcode;
       this.purchases = purchases;
    }
   
    public String getCustomerKey() {
        return this.customerKey;
    }
    
    public void setCustomerKey(String customerKey) {
        this.customerKey = customerKey;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getStreet1() {
        return this.street1;
    }
    
    public void setStreet1(String street1) {
        this.street1 = street1;
    }
    public String getStreet2() {
        return this.street2;
    }
    
    public void setStreet2(String street2) {
        this.street2 = street2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }
    public Set getPurchases() {
        return this.purchases;
    }
    
    public void setPurchases(Set purchases) {
        this.purchases = purchases;
    }

    @Override
    public String toString() {
        return "Customer{" + "customerKey=" + customerKey + ", lastName=" + lastName + ", firstName=" + firstName + ", phone=" + phone + ", street1=" + street1 + ", street2=" + street2 + ", city=" + city + ", state=" + state + ", zipcode=" + zipcode + ", purchases=" + purchases + '}';
    }

}


