package pojos;
// Generated Feb 2, 2019 9:01:49 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Purchase generated by hbm2java
 */
public class Purchase  implements java.io.Serializable {


     private Integer purchaseKey;
     private Automobile automobile;
     private Customer customer;
     private Salesperson salesperson;
     private Date dateSold;
     private int odometer;
     private BigDecimal price;

    public Purchase() {
    }

    public Purchase(Automobile automobile, Customer customer, Salesperson salesperson, Date dateSold, int odometer, BigDecimal price) {
       this.automobile = automobile;
       this.customer = customer;
       this.salesperson = salesperson;
       this.dateSold = dateSold;
       this.odometer = odometer;
       this.price = price;
    }
   
    public Integer getPurchaseKey() {
        return this.purchaseKey;
    }
    
    public void setPurchaseKey(Integer purchaseKey) {
        this.purchaseKey = purchaseKey;
    }
    public Automobile getAutomobile() {
        return this.automobile;
    }
    
    public void setAutomobile(Automobile automobile) {
        this.automobile = automobile;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Salesperson getSalesperson() {
        return this.salesperson;
    }
    
    public void setSalesperson(Salesperson salesperson) {
        this.salesperson = salesperson;
    }
    public Date getDateSold() {
        return this.dateSold;
    }
    
    public void setDateSold(Date dateSold) {
        this.dateSold = dateSold;
    }
    public int getOdometer() {
        return this.odometer;
    }
    
    public void setOdometer(int odometer) {
        this.odometer = odometer;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    @Override
    public String toString() {
        return "Purchase{" + "purchaseKey=" + purchaseKey + ", automobile=" + automobile + ", customer=" + customer + ", salesperson=" + salesperson + ", dateSold=" + dateSold + ", odometer=" + odometer + ", price=" + price + '}';
    }

}


